// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgtXDt2htmpu8fTzQr4H3jYT9Re8W-0Aw',
    appId: '1:466691410138:web:ca4c30adba03fb17d9bde3',
    messagingSenderId: '466691410138',
    projectId: 'flutter-shop-app-c2494',
    authDomain: 'flutter-shop-app-c2494.firebaseapp.com',
    databaseURL: 'https://flutter-shop-app-c2494-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-shop-app-c2494.appspot.com',
    measurementId: 'G-Y2QLDFJ1N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxSB0LTNSPpzXgUOgweHeUwCDT5_WMkVs',
    appId: '1:466691410138:android:ffcf5d61bef8a96cd9bde3',
    messagingSenderId: '466691410138',
    projectId: 'flutter-shop-app-c2494',
    databaseURL: 'https://flutter-shop-app-c2494-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-shop-app-c2494.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB44oZpl1g6KonyraBsHIxtyARjolV1VLg',
    appId: '1:466691410138:ios:0a869a089a7fbbafd9bde3',
    messagingSenderId: '466691410138',
    projectId: 'flutter-shop-app-c2494',
    databaseURL: 'https://flutter-shop-app-c2494-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-shop-app-c2494.appspot.com',
    iosClientId: '466691410138-3c3jb3n05if3296d43u3cuvc480cu2t0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomShopApp',
  );
}
